spring:
  config:
    import: "classpath:application-properties.yml"
  application:
    name: shoes-shopping-online-system

  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_NAME:ssos}
    username: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:123456}

  sql:
    init:
      mode: always
  #      url: jdbc:postgresql://localhost:5432/ssos
  #      username: postgres
  #      password: 123456

  jpa:
    hibernate:
      ddl-auto: update # Disable Hibernate's automatic schema generation

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

  threads.virtual.enabled: true # Make use of Spring Boot 3.2+ Virtual Threads support

  security.oauth2.resourceserver:
    jwt.issuer-uri: ${application-properties.keycloak-properties.server-url}/realms/${application-properties.keycloak-properties.realm-name}

  ai:
    chat:
      client:
        enabled: false

    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2
          max-tokens: 1024
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.0-flash
            temperature: 0.2
            max-output-tokens: 1024

logging.level:
  # If you are curious about how Spring Security OAuth2 works behind the scene
  org.springframework.security.oauth2: TRACE
  org.springframework.ai: INFO
  org.springframework.ai.chat.client.advisor: DEBUG
springdoc.swagger-ui:
  path: /swagger-ui
  disable-swagger-default-url: true
server:
  port: 8088
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health


